[package]
name = "invoke"
version = "0.1.0"
authors = ["Eric Butler <idealeric@gmail.com>", "Noah Durell <noah.durell@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
